### ISSUE TITLE
Raise exception if a Task is trying to send an Event that is not declared in zenaton_boot.py

### ISSUE THREAD

**Issue by florianjourda** [zenaton/zenaton-python#35]
Issue: in a task, I am sending an event MyEvent, but I forgot to import MyEvent in `zenaton_boot.py`. It seems that then Zenaton created a event from a new class 'workflow.MyEvent' on the fly instead of using 'my_module.my_workflow.MyEvent', making logic like `isinstanceof(event, MyEvent)` not working in the rest of my code downstream.

Solution:
- quick: Raise an exception when trying to create an event whose class is not imported in `zenaton_boot.py` explaining that I need to add the import
- better: have a different system for imports in `zenaton_boot.py`, like telling Zenaton to import all Zenaton objects in a tree (ìmport my_workflows`=> would also import everything under)

**Comment by florianjourda** [comment]
@pcorpet

**Comment by pcorpet** [comment]
It should work without having it in boot. See https://github.com/zenaton/zenaton-python/blob/master/zenaton/services/serializer.py#L216

The trouble is that it's reloaded from your workflow file but under a different python module `workflow.MyEvent`.

**Comment by geomagilles** [comment]
@florianjourda can you confirm it's fixed with last version of Agent ans SDK (0.3.4), please?

**Comment by pcorpet** [comment]
Yep I confirm it's fixed.

**Comment by geomagilles** [comment]
thx!
