### ISSUE TITLE
Task execution fails when passing an Event as task argument due likely to serialization issue of Event object

### ISSUE THREAD

**Issue by florianjourda** [zenaton/zenaton-python#37]
<img width="531" alt="Screen Shot 2019-06-27 at 15 08 14" src="https://user-images.githubusercontent.com/4361853/60269127-26acad80-98ee-11e9-8a84-e684ddefbcc3.png">

Exception comes from `def import_class(self, workflow_name, class_name):` where `workflow_name` = None, `class_name`= `CompleteRiderTypeformEvent` and `self.boot` = None

**Comment by pcorpet** [comment]
This should be fixed in the next release of the agent.

**Comment by geomagilles** [comment]
@florianjourda can you confirm it's fixed with last version of Agent ans SDK (0.3.4), please?

**Comment by pcorpet** [comment]
Yep, I confirm that it's fixed.
